name = "bordershop-bot"
main = "src/index.ts"
compatibility_date = "2026-05-23"
workers_dev = false
preview_urls = false

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["*/15 * * * *"]

[vars]
CATEGORIES = '["scacat_5101", "scacat_5102", "scacat_5103"]'

[[d1_databases]]
binding = "DB"
database_name = "bordershop"
database_id = "3ea00bb6-dd9e-4b0c-bc4e-b7a04d21f53f"
migrations_dir = "migrations"
